definitions:
  response.Page:
    properties:
      count:
        type: integer
      list:
        type: object
      pageIndex:
        type: integer
      pageSize:
        type: integer
    type: object
  response.PageResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/response.Page'
        type: object
      msg:
        type: string
    type: object
  response.Res:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/menu:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取JSON
      parameters:
      - description: menuName
        in: formData
        name: menuName
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: menuType
        in: formData
        name: menuType
        required: true
        type: string
      - description: path
        in: formData
        name: path
        required: true
        type: string
      - description: permission
        in: formData
        name: permission
        required: true
        type: string
      - description: action
        in: formData
        name: action
        type: string
      - description: parentId
        in: formData
        name: parentId
        type: string
      - description: isFrame
        in: formData
        name: isFrame
        type: string
      - description: sort
        in: formData
        name: sort
        type: string
      - description: visible
        in: formData
        name: visible
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      security:
      - Bearer: []
      summary: 创建菜单
      tags:
      - Menu
  /api/v1/menulist:
    get:
      description: 获取JSON
      parameters:
      - description: menuName
        in: query
        name: menuName
        type: string
      - description: visible
        in: query
        name: visible
        type: string
      - description: title
        in: query
        name: title
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      security:
      - Bearer: []
      summary: Menu列表数据
      tags:
      - Menu
  /api/v1/role/{roleId}:
    get:
      description: 获取JSON
      parameters:
      - description: roleId
        in: path
        name: roleId
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      security:
      - "": []
      summary: 获取Role数据
      tags:
      - Role
  /api/v1/rolelist:
    get:
      description: Get JSON
      parameters:
      - description: roleName
        in: query
        name: roleName
        type: string
      - description: status
        in: query
        name: status
        type: string
      - description: rolekey
        in: query
        name: rolekey
        type: string
      - description: 页条数
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            $ref: '#/definitions/response.PageResponse'
      security:
      - "": []
      summary: 角色列表数据
      tags:
      - Role
  /login:
    post:
      parameters:
      - description: admin
        in: formData
        name: username
        required: true
        type: string
      - description: admin@123
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 用户登录
      tags:
      - user
  /query:
    post:
      description: 查询登录状态，并返回user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 查询登录状态，并返回user
      tags:
      - user
  /user/add:
    post:
      parameters:
      - description: dahuang
        in: formData
        name: username
        required: true
        type: string
      - description: 大黄
        in: formData
        name: nickname
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 管理员添加用户
      tags:
      - user
  /user/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 注销登录
      tags:
      - user
swagger: "2.0"
