definitions:
  dao.ReqAddUser:
    properties:
      avatar:
        type: string
      createBy:
        type: string
      createdAt:
        type: string
      dataScope:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      nickname:
        type: string
      params:
        type: string
      password:
        type: string
      phone:
        type: string
      remark:
        type: string
      roleId:
        type: integer
      salt:
        type: string
      sex:
        type: string
      status:
        type: string
      updateBy:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
      username:
        type: string
    required:
    - nickname
    - password
    - roleId
    - username
    type: object
  dao.ReqFetchContact:
    properties:
      deptId:
        description: 父部门id，组织下的直系部门为ROOT
        type: string
      orgId:
        description: 父组织id，最顶层需要用户自己输入
        type: string
      requestType:
        description: 1：组织 2：部门
        type: integer
      serverId:
        type: integer
    required:
    - serverId
    type: object
  dao.ReqFetchUserGroup:
    properties:
      serverId:
        type: integer
      userId:
        type: string
    required:
    - serverId
    - userId
    type: object
  dao.ReqLoginUser:
    properties:
      password:
        example: "123"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  dao.ReqPing:
    properties:
      host:
        type: string
      key1:
        type: string
      key2:
        type: string
      port:
        type: string
    required:
    - host
    - key1
    - key2
    - port
    type: object
  dao.ReqQueryMsg:
    properties:
      chatType:
        description: 0:单聊 ,1:群聊
        type: integer
      pageIndex:
        description: 页索引 从1开始
        type: integer
      pageSize:
        description: 每页容量，默认10
        type: integer
      query:
        description: 搜索关键字
        type: string
      serverId:
        type: integer
      targetId:
        description: 目标userID
        type: string
      type:
        description: 消息类型，目前预留
        type: integer
      userId:
        description: 本人userID
        type: string
    required:
    - serverId
    - targetId
    - userId
    type: object
  dao.ReqSearchUser:
    properties:
      keyword:
        description: 模糊查询
        type: string
      serverId:
        type: integer
    required:
    - keyword
    - serverId
    type: object
  dao.ReqUpdateServer:
    properties:
      key1:
        type: string
      key2:
        type: string
      name:
        type: string
      orgId:
        type: string
      serverId:
        type: integer
      sort:
        type: integer
    required:
    - serverId
    type: object
  dao.ReqUpdateUser:
    properties:
      avatar:
        type: string
      createBy:
        type: string
      createdAt:
        type: string
      dataScope:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      nickname:
        type: string
      params:
        type: string
      password:
        type: string
      phone:
        type: string
      remark:
        type: string
      roleId:
        type: integer
      salt:
        type: string
      sex:
        type: string
      status:
        type: string
      updateBy:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
      username:
        type: string
    type: object
  dao.ServerDao:
    $ref: '#/definitions/model.Server'
  model.Menu:
    properties:
      action:
        type: string
      breadcrumb:
        type: string
      component:
        type: string
      createBy:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      icon:
        type: string
      is_select:
        type: boolean
      isFrame:
        type: string
      menuId:
        type: integer
      menuType:
        type: string
      name:
        type: string
      noCache:
        type: boolean
      params:
        type: string
      parentId:
        type: integer
      path:
        type: string
      paths:
        type: string
      permission:
        type: string
      routes:
        items:
          $ref: '#/definitions/model.Menu'
        type: array
      sort:
        type: integer
      title:
        type: string
      updateBy:
        type: string
      updatedAt:
        type: string
      visible:
        type: string
    required:
    - menuType
    - sort
    - title
    type: object
  model.Role:
    properties:
      createBy:
        type: string
      createdAt:
        type: string
      dataScope:
        type: string
      deletedAt:
        type: string
      menuIds:
        items:
          type: integer
        type: array
      params:
        type: string
      remark:
        type: string
      roleId:
        type: integer
      roleKey:
        type: string
      roleName:
        type: string
      roleSort:
        type: integer
      status:
        type: string
      updateBy:
        type: string
      updatedAt:
        type: string
    required:
    - menuIds
    - roleKey
    - roleName
    - roleSort
    - status
    type: object
  model.Server:
    properties:
      createBy:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      host:
        type: string
      key1:
        type: string
      key2:
        type: string
      name:
        type: string
      orgId:
        type: string
      parentId:
        type: integer
      port:
        type: string
      serverId:
        type: integer
      sort:
        type: integer
      updateBy:
        type: string
      updatedAt:
        type: string
    required:
    - host
    - key1
    - key2
    - name
    - orgId
    - parentId
    - port
    - sort
    type: object
  response.Page:
    properties:
      count:
        type: integer
      list:
        type: object
      pageIndex:
        type: integer
      pageSize:
        type: integer
    type: object
  response.PageResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/response.Page'
        type: object
      msg:
        type: string
    type: object
  response.Res:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/fetchContact:
    post:
      consumes:
      - application/json
      description: 获取通讯录树
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqFetchContact'
      responses:
        "200":
          description: '{"code": -1, "message": "获取失败"}'
          schema:
            type: string
      summary: 获取通讯录树
      tags:
      - Server
  /api/v1/fetchMsgRecord:
    post:
      consumes:
      - application/json
      description: 查找聊天记录
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqQueryMsg'
      responses:
        "200":
          description: '{"code": -1, "message": "获取失败"}'
          schema:
            type: string
      summary: 查找聊天记录
      tags:
      - Server
  /api/v1/fetchUserGroup:
    post:
      consumes:
      - application/json
      description: 查找用户群组
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqFetchUserGroup'
      responses:
        "200":
          description: '{"code": -1, "message": "获取失败"}'
          schema:
            type: string
      summary: 查找用户群组
      tags:
      - Server
  /api/v1/getinfo:
    get:
      description: 获取JSON
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 获取权限信息
      tags:
      - Info
  /api/v1/login:
    post:
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqLoginUser'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 用户登录
      tags:
      - User
  /api/v1/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 注销登录
      tags:
      - User
  /api/v1/menu:
    post:
      consumes:
      - application/json
      description: 获取JSON
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 创建菜单
      tags:
      - Menu
    put:
      consumes:
      - application/json
      description: 获取JSON
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      responses:
        "200":
          description: '{"code": -1, "message": "修改失败"}'
          schema:
            type: string
      summary: 修改菜单
      tags:
      - Menu
  /api/v1/menu/{menuId}:
    delete:
      description: 删除数据
      parameters:
      - description: menuId
        in: path
        name: menuId
        required: true
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "删除失败"}'
          schema:
            type: string
      summary: 删除菜单
      tags:
      - Menu
    get:
      description: 获取JSON
      parameters:
      - description: menuId
        in: path
        name: menuId
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 获取Menu数据
      tags:
      - Menu
  /api/v1/menulist:
    get:
      description: 获取JSON
      parameters:
      - description: visible
        in: query
        name: visible
        type: string
      - description: title
        in: query
        name: title
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: Menu列表数据
      tags:
      - Menu
  /api/v1/menurole:
    get:
      description: 获取JSON
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 根据角色名称获取菜单列表数据（左菜单使用）
      tags:
      - Menu
  /api/v1/ping:
    post:
      consumes:
      - application/json
      description: 测试服务器的连通性
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqPing'
      responses:
        "200":
          description: '{"code": -1, "message": "连接超时"}'
          schema:
            type: string
      summary: 连接测试
      tags:
      - Server
  /api/v1/query:
    get:
      description: 查询登录状态，并返回user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Res'
      summary: 查询登录状态，并返回user
      tags:
      - User
  /api/v1/role:
    post:
      consumes:
      - application/json
      description: 获取JSON
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 创建角色
      tags:
      - Role
    put:
      consumes:
      - application/json
      description: 获取JSON
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "200":
          description: '{"code": -1, "message": "修改失败"}'
          schema:
            type: string
      summary: 修改用户角色
      tags:
      - Role
  /api/v1/role/{roleId}:
    delete:
      description: 删除数据
      parameters:
      - description: roleId
        in: path
        name: roleId
        required: true
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "删除失败"}'
          schema:
            type: string
      summary: 删除用户角色
      tags:
      - Role
    get:
      description: 获取JSON
      parameters:
      - description: roleId
        in: path
        name: roleId
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 获取Role数据
      tags:
      - Role
  /api/v1/rolelist:
    get:
      description: Get JSON
      parameters:
      - description: roleName
        in: query
        name: roleName
        type: string
      - description: status
        in: query
        name: status
        type: string
      - description: rolekey
        in: query
        name: rolekey
        type: string
      - description: 页条数
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            $ref: '#/definitions/response.PageResponse'
      summary: 角色列表数据
      tags:
      - Role
  /api/v1/searchUser:
    post:
      consumes:
      - application/json
      description: 查找用户
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqSearchUser'
      responses:
        "200":
          description: '{"code": -1, "message": "获取失败"}'
          schema:
            type: string
      summary: 查找用户
      tags:
      - Server
  /api/v1/server:
    post:
      consumes:
      - application/json
      description: 添加服务器
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ServerDao'
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 添加服务器
      tags:
      - Server
    put:
      consumes:
      - application/json
      description: 修改服务器信息
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqUpdateServer'
      responses:
        "200":
          description: '{"code": -1, "message": "修改失败"}'
          schema:
            type: string
      summary: 修改服务器信息
      tags:
      - Server
  /api/v1/server/{serverId}:
    delete:
      consumes:
      - application/json
      description: 删除服务器
      parameters:
      - description: serverId
        in: path
        name: serverId
        required: true
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "删除失败"}'
          schema:
            type: string
      summary: 删除服务器
      tags:
      - Server
    get:
      description: 获取服务器信息
      parameters:
      - description: serverId
        in: path
        name: serverId
        type: string
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 获取服务器信息
      tags:
      - Server
  /api/v1/serverlist:
    get:
      description: 服务器列表
      parameters:
      - description: host
        in: query
        name: host
        type: string
      - description: name
        in: query
        name: name
        type: string
      - description: parentId
        in: query
        name: parentId
        type: integer
      - description: 页条数
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            $ref: '#/definitions/response.PageResponse'
      summary: 服务器列表
      tags:
      - Server
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: 获取JSON
      parameters:
      - description: 用户数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqAddUser'
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 创建用户
      tags:
      - User
    put:
      consumes:
      - application/json
      description: 获取JSON
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dao.ReqUpdateUser'
      responses:
        "200":
          description: '{"code": -1, "message": "修改失败"}'
          schema:
            type: string
      summary: 修改用户数据
      tags:
      - User
  /api/v1/user/{userId}:
    delete:
      description: 删除数据
      parameters:
      - description: userId
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": -1, "message": "删除失败"}'
          schema:
            type: string
      summary: 删除用户数据
      tags:
      - User
    get:
      description: 获取JSON
      parameters:
      - description: userId
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 获取用户
      tags:
      - User
  /api/v1/user/profileAvatar:
    post:
      consumes:
      - multipart/form-data
      description: 获取JSON
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 修改头像
      tags:
      - User
  /api/v1/userlist:
    get:
      description: 获取JSON
      parameters:
      - description: username
        in: query
        name: username
        type: string
      - description: phone
        in: query
        name: phone
        type: string
      - description: status
        in: query
        name: status
        type: string
      - description: 页条数
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      responses:
        "200":
          description: '{"code": -1, "message": "抱歉未找到相关信息"}'
          schema:
            type: string
      summary: 列表数据
      tags:
      - User
swagger: "2.0"
